name: Docker build

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest

    steps:

      - name: print
        run: echo "${{ toJson(github.event) }}"
        shell: bash

      - name: print
        run: echo "${{ github.event_name }}"
        shell: bash
